2025-09-21 22:40:35,061 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2025-09-21 22:41:03,213 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 22:41:03,987 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 483, in connect
    self._auth(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 814, in _auth
    raise saved_exception
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 801, in _auth
    self._transport.auth_password(username, password)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/transport.py", line 1632, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/aruba/aruba_os.py", line 21, in __init__
    return super().__init__(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1183, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: aruba_os 192.168.1.221:22

Authentication failed.

2025-09-21 22:41:05,955 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 483, in connect
    self._auth(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 814, in _auth
    raise saved_exception
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 801, in _auth
    self._transport.auth_password(username, password)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/transport.py", line 1632, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1183, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_ios 192.168.1.223:22


Authentication failed.

2025-09-21 22:52:06,345 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 22:52:09,324 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 483, in connect
    self._auth(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 814, in _auth
    raise saved_exception
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 801, in _auth
    self._transport.auth_password(username, password)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/transport.py", line 1632, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1183, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: cisco_ios 192.168.1.222:22


Authentication failed.

2025-09-21 22:52:10,020 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 622, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 415, in get_structured_data_textfsm
    output = _textfsm_parse(
             ^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 369, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 278, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 312, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 912, in ParseText
    self._CheckLine(line)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 961, in _CheckLine
    if self._Operations(rule, line):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 1043, in _Operations
    raise TextFSMError(
textfsm.parser.TextFSMError: State Error raised. Rule Line: 15. Input Line: IPv4 Address     MAC                Port         Physical Port                                      State     

2025-09-21 22:52:10,588 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 483, in connect
    self._auth(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 814, in _auth
    raise saved_exception
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 801, in _auth
    self._transport.auth_password(username, password)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/transport.py", line 1632, in auth_password
    return self.auth_handler.wait_for_response(my_event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1183, in establish_connection
    raise NetmikoAuthenticationException(msg)
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: juniper_junos 192.168.1.221:22


Authentication failed.

2025-09-21 22:54:50,169 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 22:54:53,169 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 622, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 415, in get_structured_data_textfsm
    output = _textfsm_parse(
             ^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 369, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 278, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 312, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 912, in ParseText
    self._CheckLine(line)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 961, in _CheckLine
    if self._Operations(rule, line):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 1043, in _Operations
    raise TextFSMError(
textfsm.parser.TextFSMError: State Error raised. Rule Line: 15. Input Line: IPv4 Address     MAC                Port         Physical Port                                      State     

2025-09-21 22:55:14,407 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 22:55:14,429 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-21 22:55:36,417 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 23:00:51,360 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-21 23:01:27,331 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 1 hosts
2025-09-21 23:02:07,988 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2025-09-21 23:02:22,447 -  nornir.core -  WARNING -        run() - Task 'netmiko_send_command' has not been run â€“ 0 hosts selected
2025-09-21 23:02:36,471 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 1 hosts
2025-09-21 23:02:55,859 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 1 hosts
2025-09-21 23:14:19,720 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table'], 'dry_run': False} on 3 hosts
2025-09-21 23:14:19,745 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2025-09-21 23:14:19,747 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2025-09-21 23:14:19,750 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_aoscx". Is the library installed?

2025-09-21 23:14:33,962 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table'], 'dry_run': False} on 3 hosts
2025-09-21 23:14:33,985 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2025-09-21 23:14:33,987 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_aoscx". Is the library installed?

2025-09-21 23:14:33,990 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2025-09-21 23:17:19,815 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table'], 'dry_run': False} on 1 hosts
2025-09-21 23:17:19,827 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_aoscx". Is the library installed?

2025-09-21 23:17:39,537 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['arp_table'], 'dry_run': False} on 1 hosts
2025-09-21 23:17:39,547 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2025-09-21 23:18:00,306 -  nornir.core -  WARNING -        run() - Task 'napalm_get' has not been run â€“ 0 hosts selected
2025-09-21 23:18:35,231 -  nornir.core -  WARNING -        run() - Task 'napalm_get' has not been run â€“ 0 hosts selected
2025-09-21 23:18:46,459 -  nornir.core -  WARNING -        run() - Task 'napalm_get' has not been run â€“ 0 hosts selected
2025-09-21 23:18:57,889 -  nornir.core -  WARNING -        run() - Task 'napalm_get' has not been run â€“ 0 hosts selected
2025-09-21 23:19:31,178 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:19:31,189 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "cisco_ios". Is the library installed?

2025-09-21 23:19:42,765 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:54:56,483 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-21 23:54:56,509 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2025-09-21 23:54:56,514 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-21 23:54:57,706 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:56:17,727 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:56:18,749 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:57:03,815 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:57:35,227 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-21 23:59:09,054 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-21 23:59:09,079 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2025-09-21 23:59:09,082 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:00:00,754 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:00:00,774 - nornir.core.task -    ERROR -      start() - Host 'juniper': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2025-09-22 00:00:00,776 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:00:15,537 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:00:15,559 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:01:10,171 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:01:10,197 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:01:32,117 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:01:32,139 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:02:02,539 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:02:02,561 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:02:34,566 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:02:34,589 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:02:47,087 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 3 hosts
2025-09-22 00:02:47,108 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "aruba_osx". Is the library installed?

2025-09-22 00:06:14,523 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-22 00:06:14,544 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:06:29,597 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-22 00:06:29,613 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:06:45,782 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-22 00:06:45,799 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:07:48,172 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-22 00:07:48,187 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:08:39,904 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 3 hosts
2025-09-22 00:08:39,923 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:08:58,435 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 1 hosts
2025-09-22 00:08:58,444 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are: 
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-09-22 00:09:21,482 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True} on 1 hosts
2025-09-22 00:09:24,769 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 622, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 415, in get_structured_data_textfsm
    output = _textfsm_parse(
             ^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 369, in _textfsm_parse
    tfsm_parse(raw_output, attrs)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 278, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 312, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 912, in ParseText
    self._CheckLine(line)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 961, in _CheckLine
    if self._Operations(rule, line):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 1043, in _Operations
    raise TextFSMError(
textfsm.parser.TextFSMError: State Error raised. Rule Line: 15. Input Line: IPv4 Address     MAC                Port         Physical Port                                      State     

2025-09-22 00:09:35,784 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 00:10:12,429 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 00:11:26,112 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:03:16,781 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:03:26,814 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 384, in connect
    sock.connect(addr)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/aruba/aruba_os.py", line 21, in __init__
    return super().__init__(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1168, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: aruba_os 192.168.1.222:22



2025-09-22 01:06:05,449 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:06:32,773 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:07:37,485 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:08:10,946 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:08:44,927 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:09:50,801 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:10:12,878 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:11:46,535 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:12:08,995 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:13:22,690 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:13:39,791 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:14:04,420 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:14:27,247 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:16:20,885 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:16:51,651 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:17:10,137 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:17:23,421 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:17:56,580 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:18:18,240 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:19:15,607 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:19:47,614 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:22:18,882 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:23:45,578 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:24:08,936 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:24:34,271 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:25:46,674 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:26:10,263 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:26:50,961 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:27:10,840 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:27:35,154 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:27:48,174 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:28:07,321 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:28:31,342 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:28:41,379 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:29:10,525 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:30:40,685 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:31:39,921 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:31:56,178 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:32:14,701 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 01:32:32,822 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2025-09-22 19:07:45,029 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show mac-address-table', 'use_textfsm': True, 'textfsm_template': '/home/docker/scripts/device_scanner/template/aruba_aoscx_show_mac-address-table.textfsm'} on 1 hosts
2025-09-22 19:08:12,790 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show mac-address-table', 'use_textfsm': True, 'textfsm_template': '/home/docker/scripts/device_scanner/template/aruba_aoscx_show_mac-address-table.textfsm'} on 1 hosts
2025-09-22 19:08:55,784 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show mac-address-table', 'use_textfsm': True, 'textfsm_template': '/home/docker/scripts/device_scanner/template/aruba_aoscx_show_mac-address-table.textfsm'} on 1 hosts
2025-09-22 19:10:45,443 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_mac-address-table.textfsm'} on 1 hosts
2025-09-22 19:11:13,160 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:13:16,723 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:14:43,673 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:16:21,065 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show mac-address-table', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_mac-address-table.textfsm'} on 1 hosts
2025-09-22 19:16:22,698 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 622, in structured_data_converter
    structured_output_tfsm = get_structured_data_textfsm(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 434, in get_structured_data_textfsm
    return _textfsm_parse(
           ^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/utilities.py", line 367, in _textfsm_parse
    tfsm_parse(raw_output, templates=template_file)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 278, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/clitable.py", line 312, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 912, in ParseText
    self._CheckLine(line)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 961, in _CheckLine
    if self._Operations(rule, line):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/textfsm/parser.py", line 1043, in _Operations
    raise TextFSMError(
textfsm.parser.TextFSMError: State Error raised. Rule Line: 13. Input Line: No MAC entries found.

2025-09-22 19:20:45,705 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:20:55,739 - nornir.core.task -    ERROR -      start() - Host 'aruba': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1146, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/paramiko/client.py", line 384, in connect
    sock.connect(addr)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 460, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/aruba/aruba_os.py", line 21, in __init__
    return super().__init__(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 495, in __init__
    self._open()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 500, in _open
    self.establish_connection()
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/netmiko/base_connection.py", line 1168, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: aruba_os 192.168.1.222:22



2025-09-22 19:23:27,732 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:26:30,564 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:29:16,065 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:29:46,422 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:30:19,259 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all vrfs', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:30:31,970 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all vrf', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:30:42,944 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:32:56,513 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:34:45,673 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:35:29,940 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:35:46,922 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:37:30,255 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:37:46,003 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:42:00,529 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:43:50,453 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:45:55,009 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:52:11,205 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:52:58,744 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:54:32,825 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:58:51,538 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 19:59:16,043 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:00:26,342 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:00:51,595 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:02:12,941 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:02:56,621 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:03:25,470 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:03:50,605 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 20:04:38,996 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:05:40,942 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:06:37,917 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:07:30,709 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:07:43,214 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:07:58,066 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table'], 'use_textfsm': True} on 1 hosts
2025-09-22 20:07:59,172 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
                ^^^^^^^^^^^^^^^^^
TypeError: IOSDriver.get_arp_table() got an unexpected keyword argument 'use_textfsm'

2025-09-22 20:08:23,333 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table'], 'use_textfsm': True} on 1 hosts
2025-09-22 20:08:24,218 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
                ^^^^^^^^^^^^^^^^^
TypeError: IOSDriver.get_arp_table() got an unexpected keyword argument 'use_textfsm'

2025-09-22 20:09:22,804 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table'], 'use_textfsm': True} on 1 hosts
2025-09-22 20:09:23,888 - nornir.core.task -    ERROR -      start() - Host 'cisco': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
                ^^^^^^^^^^^^^^^^^
TypeError: IOSDriver.get_arp_table() got an unexpected keyword argument 'use_textfsm'

2025-09-22 20:10:11,196 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:11:32,993 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:12:03,862 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:12:34,063 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:12:52,205 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:13:15,947 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:13:38,811 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:14:47,285 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:23:37,681 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:41:23,411 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:43:54,621 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 20:47:19,534 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 1 hosts
2025-09-22 21:06:27,766 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 2 hosts
2025-09-22 21:09:24,389 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table']} on 2 hosts
2025-09-22 21:10:27,825 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_arp_table(vrf: str= )']} on 2 hosts
2025-09-22 21:10:28,896 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 43, in napalm_get
    method = getattr(device, getter)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IOSDriver' object has no attribute 'get_arp_table(vrf: str= )'

2025-09-22 21:10:29,109 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 43, in napalm_get
    method = getattr(device, getter)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IOSDriver' object has no attribute 'get_arp_table(vrf: str= )'

2025-09-22 21:11:47,314 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ["get_arp_table(vrf: str = '')"]} on 2 hosts
2025-09-22 21:11:48,568 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 43, in napalm_get
    method = getattr(device, getter)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IOSDriver' object has no attribute 'get_arp_table(vrf: str = '')'

2025-09-22 21:11:48,771 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/python/nornir/mac_address_export/nornir/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 43, in napalm_get
    method = getattr(device, getter)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IOSDriver' object has no attribute 'get_arp_table(vrf: str = '')'

2025-09-22 21:13:11,153 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': {'get_arp_table': {'vrf': ''}}} on 2 hosts
2025-09-22 21:13:33,499 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': {'get_arp_table': {'vrf': 'Cust_A'}}} on 2 hosts
2025-09-22 21:43:03,386 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp vrf-all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 21:43:48,592 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp vrf-all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 21:44:05,454 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp vrf', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 21:44:17,585 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp vrf all', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 21:44:29,515 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all-vrfs', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
2025-09-22 21:45:03,505 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp all-vrfs', 'use_textfsm': True, 'textfsm_template': '/home/admin/python/nornir/mac_address_export/templates/aruba_aoscx_show_arp_all-vrfs.textfsm'} on 1 hosts
